project:
  type: website
  output-dir: docs

website:
  title: "angabrio.github.io"
  favicon: img/icon.png
  navbar:
    background: rgba(34, 44, 117)
    foreground: white
    search: true
    right:
      - href: index.qmd
        text: Home
      - posts.qmd
      - projects.qmd
      - publications.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Andrea Gabrio"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    mainfont: Montserrat
    fontsize: 1.2rem
    fontcolor: black
    linkcolor: rgb(127,140,180)
    monofont: courier new
    toc: true

editor: source

