{
  "hash": "c330669f053837bd3512d011c99db7ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In which Dutch province do people travel the most?\"\ndescription: \"\"\nauthor:\n  - name: Andrea Gabrio\n    url: https://angabrio.github.io/agabriosite2/\n    orcid: 0000-0002-7650-4534\n    affiliation: Maastricht University\n    affiliation-url: https://www.maastrichtuniversity.nl/research/methodology-and-statistics\ndate: 2024-09-14\ncategories: [Quarto, R, Academia] # self-defined categories\n#citation: \n#  url: https://samanthacsik.github.io/posts/2022-10-24-my-blog-post/ \nimage: featured.jpg\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n\n\n![](featured.jpg){fig-align=\"center\"}\nHello dear readers, I hope everything is well with you and welcome back for another post on my site. Today I would like to continue the little exercise I started last time where I played a bit using some Dutch data related to the different provinces of the country to make some comparisons between them. Again, I apologise to my readers who are looking forward to some more health economics topic, but I really want to continue the previous topic with some additional fun examples.\n\nWhat I am focussing today is still about using some Dutch-province level data, this time taken directly from the [CBS website](https://opendata.cbs.nl/statline/#/CBS/en/dataset/84710eng/table?ts=1726493735067) and related to the average number of travels per person per year. My  basic idea is very simple. Which province has the largest average number of travels per year? and can we also identify some temporal trend? in order to answer this question I have taken from the above link information about the average number of travels per person per year for each of the $12$ provinces of the Netherlands over a period of $6$ years, between 2018 and 2023.\n\nAs usual, let's start by drawing a map of the country divided into provinces:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tmap)\ntmap_mode(\"plot\")\ndata(NLD_prov)\ntm_shape(NLD_prov) +\n  tm_borders(lwd=2) + \n  tm_fill(\"name\") + \n  tm_format(\"NLD\", title=\"Dutch provinces\", bg.color=\"white\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\nNext, let's download the CBS data we are interested as a `.csv` file, import it into `R` and let's explore the data. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNLD_prov_travel <- read.csv(\"per_person__travel_modes__travel_purpose_16092024_155133.csv\", header = T, sep = \";\")\n\n#create a subset of the dataset and rename the variables\nNLD_prov_travel <- NLD_prov_travel[,5:7]\nnames(NLD_prov_travel) <- c(\"Province\",\"Year\",\"Travels\")\n\n#let's extract the travel data for all provinces for 1 year first, say 2023\nNLD_prov_travel_2023 <- NLD_prov_travel[NLD_prov_travel$Year==2023,]\n\n#see the data\nNLD_prov_travel_2023\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Province Year Travels\n6      Groningen (PV) 2023     994\n12       Fryslân (PV) 2023     995\n18       Drenthe (PV) 2023     988\n24    Overijssel (PV) 2023    1054\n30     Flevoland (PV) 2023     936\n36    Gelderland (PV) 2023    1036\n42       Utrecht (PV) 2023    1029\n48 Noord-Holland (PV) 2023     954\n54  Zuid-Holland (PV) 2023     945\n60       Zeeland (PV) 2023     974\n66 Noord-Brabant (PV) 2023    1023\n72       Limburg (PV) 2023    1011\n```\n\n\n:::\n:::\n\n\n\nWe can see that in 2023 it appears that Overijssel, Gelderland, Utrecht, and Noord-Brabant were the provinces associated with most average number of travels per person (above $1020$ travels). It could interesting to get some information about how the number of travels has changed over time for each province. To achieve this we can try to compute some summary statistics:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load package\nlibrary(data.table)\n#create custom summary function\nmy.summary <- function(x, na.rm=TRUE){list(n= length(x),\n                                  Mean=mean(x),\n                                  SD=sd(x),\n                                  Median=median(x), \n                                  Min=min(x),\n                                  Max=max(x))}\n#summarise data\nsum_data_travel <- setDT(NLD_prov_travel)[, unlist(lapply(.SD, my.summary),recursive=FALSE), Province]\n\n#extract and display relevant data\nsum_data_travel.dt <- sum_data_travel[,c(1,8:13)] \nsum_data_travel.dt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Province Travels.n Travels.Mean Travels.SD Travels.Median\n                <char>     <int>        <num>      <num>          <num>\n 1:     Groningen (PV)         6     941.3333   72.39797          959.5\n 2:       Fryslân (PV)         6     960.5000   39.53606          972.0\n 3:       Drenthe (PV)         6     976.1667   55.27537          985.0\n 4:    Overijssel (PV)         6    1002.1667   67.49049         1034.0\n 5:     Flevoland (PV)         6     905.0000   58.61058          920.5\n 6:    Gelderland (PV)         6     999.0000   59.04574         1026.0\n 7:       Utrecht (PV)         6     992.8333   65.26689         1023.5\n 8: Noord-Holland (PV)         6     930.1667   65.12885          950.5\n 9:  Zuid-Holland (PV)         6     923.0000   64.91225          942.5\n10:       Zeeland (PV)         6     962.0000   55.20507          979.0\n11: Noord-Brabant (PV)         6     983.0000   49.52979         1005.0\n12:       Limburg (PV)         6     963.1667   56.86973          985.5\n    Travels.Min Travels.Max\n          <int>       <int>\n 1:         831        1024\n 2:         908         998\n 3:         880        1028\n 4:         886        1054\n 5:         820         980\n 6:         905        1046\n 7:         888        1056\n 8:         820        1006\n 9:         814         989\n10:         858        1015\n11:         904        1023\n12:         872        1011\n```\n\n\n:::\n:::\n\n\n\nCreating summary statistics per Province over a period of 6 years (2018-2023), we can see that on average Overijssel still places at the top with a mean number of travels per person of $1002$, followed by Gelderland ($999$) and Utrecht ($992$), while all other Provinces seem to fall a bit behind with very similar values between $900$ and $976$. However, we also notice that, for some Provinces, median values are a bit different from means (typically higher), with also some minimum and maximum values that can be quite extreme in some cases. So, let's have a look at the shape of the data distribution. For example, we may plot via histograms the travel data by Province over the 6-year period considered.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(data = NLD_prov_travel, aes(x = Travels)) + geom_histogram(binwidth = 30, fill=\"white\", color = \"black\") + facet_wrap(~Province, scales = \"free\") + theme_classic()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nAlthough 6 data points per Province is not a lot to look at, we can notice that for some Provinces the distribution of the number of travels is skewed, therefore suggesting how the mean perhaps is not a good indicator for these data. \n\nWhat at this point if we want to try and make a prediction of what the number of travels would be for each Province in 2024? and what about the expected number of travels over the 6 year period across all Provinces? Well, for that we need some **inferential statistics**! For example, taking into account the time dependence of the 6 observations per Province, let's try to fit a linear mixed effects model including a random error term to capture the clustering nature of the data at the level of the Provinces:\n\n$$\n\\text{Travel}_{ij} = \\beta_0 + \\beta_1 \\times \\text{Year} + \\omega_j + \\varepsilon_{ij}\n$$\n\nwhere: $\\text{Travel}_{ij}$ refers to the number of travels per person for Province $i$ in Year $j$, while $\\beta_0$ is the intercept, $\\beta_1$ is the year regression coefficient, $\\varepsilon_{ij}$ and $\\omega_j$ are the random error term and the Province-specific random effect term.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load package\nlibrary(lme4)\nfm <- lmer(Travels ~ Year + (1 | Province), data = NLD_prov_travel)\n#define new data for prediction\nnewdata <- expand.grid(\n  Year = c(2024),\n  Province = unique(NLD_prov_travel$Province)\n)\n#predict\nfm_pred <- predict(fm, newdata = newdata)\nnames(fm_pred) <- unique(NLD_prov_travel$Province)\n\n#look at predictions\nfm_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Groningen (PV)       Fryslân (PV)       Drenthe (PV)    Overijssel (PV) \n          948.6030           955.9821           962.0137           972.0237 \n    Flevoland (PV)    Gelderland (PV)       Utrecht (PV) Noord-Holland (PV) \n          934.6147           970.8045           968.4304           944.3038 \n Zuid-Holland (PV)       Zeeland (PV) Noord-Brabant (PV)       Limburg (PV) \n          941.5447           956.5596           964.6445           957.0087 \n```\n\n\n:::\n:::\n\n\n\nWe can see that, according to the model predictions Overijssel still is associated with the largest number of travels even in 2024, followed by Gelderland and Utrecht, although the difference now seems a little bit smaller compared to what observed from the descriptive analysis of the data. Finally, we can also try to obtain an estimate of the average number of travels across Years and Provinces. This can be done, if we consider Year as a continuous variable, by setting its value equal to the average across the years considered ($\\bar{\\text{Year}}=\\text{E}[\\text{Year}]_i$, for $i=,2018,2019,\\ldots,2023$), generate the predictions by Province, and then take the expectation across them.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#define new data for prediction\nnewdata <- expand.grid(\n  Year = c(mean(2018:2023)),\n  Province = unique(NLD_prov_travel$Province)\n)\n#predict\nfm_pred_avg <- predict(fm, newdata = newdata)\nnames(fm_pred_avg) <- unique(NLD_prov_travel$Province)\n\n#look at predictions\nmean(fm_pred_avg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 961.5278\n```\n\n\n:::\n:::\n\n\n\nSo, based on the model and data, we would expect an average number of travels per person across Provinces between 2018-2023 of about 961.53.  \n\nI hope you enjoyed this little exercise as much as I did. It is a nice distraction from the usual work I do and a bit of fesh air. But no worries, I will soon come back to talk more about health economics and Bayesian statstics!\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}