{
  "hash": "b4a0706327aec513cca70508304d5ac3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A quick intro on medical statistics\"\ndescription: \"\"\nauthor:\n  - name: Andrea Gabrio\n    url: https://angabrio.github.io/agabriosite2/\n    orcid: 0000-0002-7650-4534\n    affiliation: Maastricht University\n    affiliation-url: https://www.maastrichtuniversity.nl/research/methodology-and-statistics\ndate: 2025-08-05\ncategories: [Quarto, R, Academia, Medical Statistics] # self-defined categories\n#citation: \n#  url: https://samanthacsik.github.io/posts/2022-10-24-my-blog-post/ \nimage: featured.jpg\nbibliography: references.bib\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n\n\nHello dear readers, and welcome back to a new post on this blog. Today I am finally entering my holidays period and therefore I look forward to enjoy a nice vacation period over the next couple of weeks. Before I do that, however, I thought it would be nice to post something light here (so no heavy math, promised!), taking this chance to talk about something I always wanted but for which I never found enough time. In particular, today's topic is very close to what many medical researchers do in their work, i.e. analysing some medical data using basic statistical methods. Over the past few years I have collaborated with several medical researchers who seem to always struggle with interpreting the statistical output of their work. They seem to know how to produce standard statistical output to summarise their research but often they feel uncomfortable on interpreting said output. I know this is probably due to a lack of statistical background in their education but since this is part of their work I believe it should be important that they try to keep up-to-date with current statistical practice in their field and know how to properly interpret statistical output that they produce themselves. \n\nWell, nowadays we all know that mnay AI websites and tools exist that can aid researchers in the generation of the output and perhaps even suggest some interpretation if adequately asked. However, I must confess that many times this type of interpretations are lacking or even incorrect and therefore I would suggest researchers to refrain from an indiscriminate use of AI help as it can be quite dangerous if they are not aware of the possible mistakes such tools can make. So, at last for the moment, statisticians are still needed to be really sure of what you are saying is correct and hopefully this post will provide some basic reference for those who are interested in the topic. For today, let's just start from the very basics, and perhaps I will expand the topic in future posts as I am also eager to start my holidays.\n\n## Background\n\nIn medicine we typically distinguish two main types of study design, i.e. experimental and observational. The first one is usually aimed at developing new treatments and identify association between diseases and possible causes based on the people's characteristics. The second one is often aimed at investigating risk factors for epidemic. In general, any study has a specific objective, such as the identification of: possible causes for a disease, information about common data features, comparison of results with respect to a non-affected group with similar features of the affected ones, establish robust findings by investigating risk of disease in different areas.  \n\nThe first official type of experimental study under the label of a *randomised control trial* is dated 1948 and was a streptomycin trial on Tuberculosis. The study enrolled $107$ patients from $7$ hospitals with acute progressive bilateral pulmonary tuberculosis and randomised them to either of two treatments: daily streptomycin + bed rest (intervention group) or bed rest alone (control group). The main outcomes of interest were X-ray improvement and death. Since then, publicly-funded clinical trials play an important role in medical statistics as they provided important contributions in many disease areas in terms of: development of new treatments, progressing treatments and improving survival/reduction of deaths, etc... Medical/Bio-statistics is a quite-well recognised discipline since the late 1940s which has continuously evolved over the years and has been subject to many debates. In particular, in many cases there have been discussions on possible issues affecting the filed, such as: vague definitions of trial aims, poor study design, unreliable date, inappropriate analysis and incorrect conclusions. Much of these problems are related to the fact that medical statistics is a very specialised area, i.e. experts and specialists (including statisticians) are needed to provide help with important aspects of research. They contribution is needed in order to: help with defining clear and precise aims for the trial, avoid bias due to bad study design, develop/evaluate methods to analyse the data, and help with interpretation of results.   \n\n# Measures of health\n\nIn order to ensure that a trial has a clear and precise objective, a key concept is the distinction between outcome and exposure variables in the context of a statistical analysis:\n\n  1. The *outcome* variable is the focus of the research, i.e. a trial whose aim is to find a treatment that can reduce cholesterol levels in a group of patients should have *cholesterol levels* as the main outcome.\n  \n  2. The *exposure* variables are those that may influence the outcome, i.e. type of treatment.  \n\nIn general, the aims of health studies include some form of: determining the risk factors for a given health outcome, identifying geographic patterns, describe the course of an health outcome, develop preventive measures, plan health services, provide administrative planning data. \nDescriptive statistics are routinely used to summarise the variables of interest in a study. They differ according to the specific type of variables considered: mean/median for continuous outcomes, incidence/prevalence rates, proportions, odds for binary/time to event outcomes. Often, when the objective of the tial is to make some comparison between groups of patients (e.g. based on treatment allocation), summary measures adopted include: mean difference for continuous outcomes, risk/rate/odds ratio, risk/rate difference for binary outcomes. It is important to remember that the suitability of a given summary measure compared to another (e.g. risk vs odds ratio) should also depend on the study design and objective.\n \n## Descriptive measures for binary/time to event outcomes\n\nOne key summary measure for binary outcomes are: \n\n  1. Incidence: number of cases in a specified time period\n  \n  2. Prevalence: number of people in a population who have a disease at a given point in time\n\nThe two concepts are different but connected in that each incident case enters a prevalence pool and remains there until either recovery or death occurs, while prevalence depends on incidence and duration, i.e. Prevalence $=$ incidence $\\times$ average duration. As a result, if recovery and deaths are low, even a low incidence can produce a high prevalence. Diseases with large incidence rates may have low prevalence if they are rapidly fatal.\n\nAnother popular measure is the Risk (proportion) which is defined as the ratio between the number of subjects with event of interest ($x$) and the total number of subjects at risk ($n$), i.e. $\\frac{x}{n}$. As an example, let's consider an hypothetical cohort study where $7989$ men at risk of stroke were followed for $12$ years and interest was to understand whether smoking was a risk factor (exposure) for the event stroke (outcome). Consider the hypothetical output from the study being represented in @tbl-stroke.\n\n\n\n::: {#tbl-stroke .cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n             Smok - Yes Smok - No Total\nStroke - Yes        171       117   288\nStroke - No        3264      4437  7701\nTotal              3435      4554  7989\n```\n\n\n:::\n:::\n\n\n\nWe can see that the overall risk among smokers is computed as: $\\frac{171}{3435}=0.049$.\n\nAnother summary measure for binary outcomes are the odds, which are defined as the ratio between the number of subjects with event of interest ($x$) and the difference between the total number of subjects at risk and those with the event of interest ($n-x$), that is $\\frac{x}{(n-x)}$. Convenient mathematical properties of this measure ensure that, even when the risk of disease within exposure group is distorted, they can still work when using relative measures of comparison. Going back to the example in @tbl-stroke, we can see that the odds of having a stroke for smokers are: $\\frac{171}{3435-171}=0.05$.\n\nIt is important to mention that there is a direct relation between odds and risk since: Risk $= \\frac{x}{n}$ and odds $=\\frac{x}{(n-x)}$, which means we can define odds $= \\frac{\\text{risk}}{1-\\text{risk}}$ and risk $= \\frac{\\text{odds}}{(1+\\text{odds})}$. \n\nAnother summary measure for binary outcomes is the rate, usually applicable to follow-up studies. Indeed, its computation requires the calculation of person time, i.e. the time a person remained in the study (e.g. until event of interest occurred) and the sum over all subjects time, i.e. rate $= \\frac{\\text{number of subjects with event of interest}}{\\text{total time at risk by the study population}}$. As an example, let's consider an hypothetical follow-up study over a period of five years and that we record for each of the four persons enrolled in the study whether the event \"disease\" has occurred. Imagine that over the study period we only observe a single person experiencing the event of the end of year 2, while for all the other three no event was observed until the end of the study period: two of them completed the study with no event, while one was lost to follow up at year 4. Thus, we can compute the rate as $= \\frac{1}{5+5+4+2}=\\frac{1}{16}=0.0625$. An advantage of using rates over risks is that subjects in the study may not be followed for equal lengths of time, which may make risks and odds distorted measures. \n\n## Measures of difference/association\n\nMany summary measures are used to compare disease/health outcome risks/rates between groups under the assumption that risks/rates in one group (i.e. exposed) are comparable to those in another group (i.e unexposed). Exposure may be defined according to some specific \"risk factors\" suspected of causing the disease or of protecting against it. To investigate association between risk factors and disease, it is common to compare the incidence of disease among exposed with respect to that among unexposed. There are mainly two types of these measures: relative (e.g. ratio) or absolute (difference).\n\nRelative measure estimate the magnitude of an association between exposure and disease, indicating how much more likely the exposed group is to develop disease than the unexposed group. Often, a value of $1$ for these measures means no difference between group, while a value above/below $1$ shows an adverse/protective effect of the exposure. The most commonly used measures are:\n\n  1. Risk ratio $= \\frac{\\text{risk in exposed group}}{\\text{risk in unexposed group}}$\n\n  2. Odds ratio $= \\frac{\\text{odds in exposed group}}{\\text{odds in unexposed group}}$\n\n  3. Rate ratio $= \\frac{\\text{rate in exposed group}}{\\text{rate in unexposed group}}$\n\nThese measures only provide point estmiates for the quantity of interest but quantification of the uncertainty surrounding these estimates is also often of great importance. Each of them has a different way to compute these measures of uncertainty, often represented in terms of some form of $95\\%$ confidence interval. Consider the generic data in tabular format shown in @tbl-ci\n\n\n\n::: {#tbl-ci .cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Exposure No Exposure\nDisease    \"a\"      \"b\"        \nNo Disease \"c\"      \"d\"        \n```\n\n\n:::\n:::\n\n\n\nWe may compute a $95\\%$ confidence interval for a risk ratio (RR) using the following quantities:\n\n  1. RR $= \\frac{a}{(a+c)}/\\frac{b}{(b+d)}$\n  \n  2. SE log RR $= \\sqrt{\\frac{1}{a}-\\frac{1}{(a+c)}+\\frac{1}{b}-\\frac{1}{(b+d)}}$\n\nand the final interval is obtained using Normal sampling distribution approximations as: estimated log RR $\\pm 1.96 \\times$ SE of estimated log RR. Note that by taking the exponent of the CI limits for log RR, it is possible to obtain the corresponding limits for RR. \n\nWe may compute a $95\\%$ confidence interval for an odds ratio (OR) using the following quantities:\n\n  1. OR $= \\frac{a}{c}/\\frac{b}{d}$\n  \n  2. SE log OR $= \\sqrt{\\frac{1}{a}+\\frac{1}{b}+\\frac{1}{c}+\\frac{1}{d}}$\n\nand the final interval is obtained using Normal sampling distribution approximations as: estimated log OR $\\pm 1.96 \\times$ SE of estimated log OR. Note that by taking the exponent of the CI limits for log OR, it is possible to obtain the corresponding limits for OR. \n\nWe may compute a $95\\%$ confidence interval for an rate ratio using the following quantities:\n\n  1.  $d_1 =$ number of deaths in exposed group\n  \n  2.  $d_0 =$ number of deaths in unexposed group\n  \n  3. SE log rate ratio $= \\sqrt{\\frac{1}{d_1}+\\frac{1}{d_0}}$\n\nand the final interval is obtained using Normal sampling distribution approximations as: estimated log rate ratio $\\pm 1.96 \\times$ SE of estimated log rate ratio. Note that by taking the exponent of the CI limits for log rate ratio, it is possible to obtain the corresponding limits for rate ratio. \n\nNote that, in general, risk ratio are easier to interpret than OR or rate ratio since they are effectively a measure of relative risk, which is true for the other two measures only when the disease are very rare.\n\nA limitation of these relative measures is that they fail to distinguish between huge and trivial exposure effects, i.e. the same relative risk measure may be computed using quite different risk differences between the groups. For example: 1) risk exposed $=0.096$ and unexposed $=0.028$ so that RR $=3.42$; 2) risk exposed $=0.96$ and unexposed $=0.28$ so that RR $=3.42$; 1) risk exposed $=0.0000096$ and unexposed $=0.0000028$ so that RR $=3.42$.\n\n## Absolute measures \n\nWhen interest is in estimating the extent to which adverse outcomes would disappear if we remove exposure, then relative measures are not enough and we also want to estimate the so-called risk/rate difference between the groups, i.e. difference $=$ risk/rate in exposed group $-$ risk/rate in unexposed group. Usually, when the difference takes value $0$ means absence of a difference between the groups, while when it is above/below $0$ it means presence of a greater/smaller risk in the exposed group.\n\nAbsolute measures are often interpreted as estimates of the amount of risk/rate that is attributable to the exposure. Similarly to relative measures, also point estimates of absolute measures may be accompanied by measures of uncertainty. For example, SE for risk difference may be directly computed as: $\\sqrt{R_1\\times(1-R_1)/n_1+R_2\\times(1-R_2)/n_2}$, where $R_1$ and $n_1$ are the risk and number of individuals in the exposed group, while $R_2$ and $n_2$ are the risk and number of individuals in the unexposed group. \n\nWe can also see that, unlike relative measures, absolute measures such as the risk difference (RD) are able to distinguish between different magnitudes of exposure effects. Using the examples above: 1) risk exposed $=0.096$ and unexposed $=0.028$ so that RD $=0.068$; 2) risk exposed $=0.96$ and unexposed $=0.28$ so that RD $=0.68$; 1) risk exposed $=0.0000096$ and unexposed $=0.0000028$ so that RD $=0.0000068$.\n\n## Summary\n\n  a. Odds ratio, rate ratio, relative risk compare the relative likelihood of an event occurring between two groups.\n  \n  b. Relative risk is easier to interpret but some designs prevent its calculation.\n  \n  c. If the disease is rate, then the three relative measures are all very similar to each other.\n  \n  d. Differences in risk and rates can also be measured in absolute terms, depending on the type of study.\n  \n  e. It may be useful to estimate both relative and absolute measures as they convey different types of information.\n\n\nSo, what do you think folks? did you find this sort of quick summary useful? I hope so as I have enjoyed myself in writing up this post. Perhaps I will follow this with more posts like this in the future. Till next time!\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}